#!/bin/sh
# Applications you want to run with fluxbox.

#Start up mate settings
exec /usr/bin/mate-settings-daemon &

#Start up mate-power manager
exec mate-power-manager &

#Start up mate-volume-control
exec mate-volume-control-applet &

#Start default applications
exec sensible-browser &
exec thunderbird &

#Startup network manager
#exec Networkmanager &
exec nm-applet &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "${HOME}/.fluxbox/log"
