#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/dotfiles/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/.zprofile"
fi
